'use strict';
const $ = s => document.querySelector(s);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let previewURL = null, discoveryRows = [], browserStream = null, browserRequest = 0;
const cameraFeeds=new Map(),cameraRecordings=new Map();
let enrollmentPhotos=[],enrollmentCameraId=null;
let token = sessionStorage.getItem('sentinel-token'), currentUser = null, generation = 0;
const titles = {home:'Overview',dashboard:'Dashboard',cameras:'Cameras',biometrics:'Biometrics',permissions:'Permissions',users:'Users',settings:'Configuration'};
const admin = () => currentUser?.role === 'admin';
async function api(path, options = {}) {
  const formBody=options.body instanceof URLSearchParams||options.body instanceof FormData;
  const response = await fetch('/api' + path, {...options, headers:{...(token ? {Authorization:'Bearer ' + token}:{}), ...(formBody ? {} : {'Content-Type':'application/json'}), ...options.headers}});
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    if(response.status === 401 && !path.startsWith('/auth/login')) {token=null;currentUser=null;sessionStorage.removeItem('sentinel-token');updateSession();}
    throw new Error(Array.isArray(data.detail) ? data.detail.map(x => x.msg).join('; ') : data.detail || 'Unable to connect. Please try again.');
  }
  return data;
}
function updateSession(){ $('#session-status').textContent=currentUser ? `${currentUser.full_name || currentUser.username} · ${currentUser.role}` : 'Guest workspace';$('#session-button').textContent=currentUser ? '↪' : '↗';$('#session-button').setAttribute('aria-label',currentUser?'Sign out':'Sign in');}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500);}
function heading(title, description, action=''){return `<div class="page-heading"><div><span class="eyebrow">YOUR SECURITY WORKSPACE</span><h1>${title}</h1><p class="sub">${description}</p></div>${action || `<span class="date">${new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date())}</span>`}</div>`;}
function empty(title,detail,action=''){return `<div class="empty"><strong>${title}</strong>${detail}${action}</div>`;}
function signInPanel(){return `<section class="panel">${empty('Your workspace is ready','Sign in to view live metrics and manage your connected spaces.','<br><button class="button primary" data-action="login">Sign in to workspace ↗</button>')}</section>`;}
function stats(summary,cameras){return `<div class="stats">${[['Registered cameras',cameras?.length,'Configured devices','▣'],['Authorized people',summary?.authorized_people,'Active biometric profiles','♧'],['Access attempts',summary?.access_attempts_24h,'In the last 24 hours','⇥'],['Open alerts',summary?.unresolved_alerts,'Awaiting review','◇']].map(([label,value,note,icon])=>`<article class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><div class="stat-value">${value ?? '—'}</div><span class="stat-note">${note}</span></article>`).join('')}</div>`;}
function modules(){return `<div class="section-head"><h2>A little control. A lot of confidence.</h2><span>Your workspace, connected</span></div><div class="modules">${[['cameras','▣','Keep an eye on every space','View your camera inventory and configure detection for each location.','Manage cameras'],['permissions','◇','The right access, for everyone','Manage biometric access and decide who can enter each zone.','Manage permissions'],['users','♧','People at the heart of security','View your team, configure accounts, and manage system roles.','Manage users']].map(([page,icon,title,description,link])=>`<a class="module" href="#${page}"><span class="module-icon">${icon}</span><h3>${title}</h3><p>${description}</p><span class="module-link">${link}<span>↗</span></span></a>`).join('')}</div>`;}
function stopBrowserStream(){
 if(!browserStream)return;
 browserStream.getVideoTracks().forEach(track=>track.onended=null);
 browserStream.getTracks().forEach(track=>track.stop());browserStream=null;
}
function clearPreview(){browserRequest++;stopBrowserStream();if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null;}}
function clearCameraFeeds(){
 cameraFeeds.forEach(feed=>{feed.stopped=true;feed.controller?.abort();});cameraFeeds.clear();
 cameraRecordings.forEach(recording=>{if(recording.recorder?.state!=='inactive')recording.recorder.stop();if(recording.url)URL.revokeObjectURL(recording.url);recording.stream?.getTracks().forEach(track=>track.stop());});cameraRecordings.clear();
}
function clearEnrollmentPhotos(){enrollmentPhotos.forEach(photo=>URL.revokeObjectURL(photo.url));enrollmentPhotos=[];}
async function render(){
 clearPreview();clearCameraFeeds();if($('#modal').open)$('#modal').close();
 const version=++generation;const page=titles[location.hash.slice(1)] ? location.hash.slice(1) : 'home';
 $('#breadcrumb').textContent=titles[page];document.title=`${titles[page]} · Sentinel`;
 document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const main=$('#main');main.innerHTML='<div class="loading">Loading your workspace…</div>';
 try{
 let content='';
 if(page==='home'||page==='dashboard'){
   const [summary,cameras]=token?await Promise.all([api('/dashboard/summary'),api('/cameras')]):[null,null];
   content=heading(page==='home'?'Everything in sight. Everything in control.':'A clearer view of your security.',page==='home'?'Welcome to Sentinel. A calmer way to manage access to your spaces.':'Live access metrics from the last 24 hours.');
   if(page==='home')content+=`<section class="hero"><div><span class="eyebrow">CONNECTED SPACES. CONFIDENT DECISIONS.</span><h2>Security starts with<br>a complete picture.</h2><p>Bring your cameras, people, and access permissions together in one simple workspace.</p><a class="button" href="#dashboard">Open dashboard <span>↗</span></a></div><div class="radar" aria-hidden="true"><div class="shield">✓</div></div></section>`;
   content+=stats(summary,cameras);
   if(page==='home')content+=modules();
   if(page==='dashboard'&&summary){const total=summary.access_attempts_24h;content+=`<section class="panel"><div class="panel-head"><h2>Access at a glance</h2><span class="badge">Last 24 hours</span></div><div class="meter-row">${[['Granted',summary.granted_24h],['Denied',summary.denied_24h]].map(([label,value])=>{let percent=total?Math.round(value/total*100):0;return `<div class="meter"><div class="meter-circle" style="--value:${percent}"><span>${total?percent+'%':'—'}</span></div><h2>${label}</h2><p>${value} of ${total} attempts</p></div>`;}).join('')}<div class="meter"><div class="meter-circle"><span>${summary.unresolved_alerts}</span></div><h2>Open alerts</h2><p>Unresolved security events</p></div></div></section>`;}
   if(!token)content+=signInPanel();
   else if(admin()){const logs=await api('/logs/access?limit=6');content+=`<section class="panel"><div class="panel-head"><h2>Recent activity</h2><span class="badge neutral">Latest access events</span></div>${logs.length?table(['Time','Camera / zone','Result'],logs.map(row=>`<tr><td>${escapeHTML(new Date(row.timestamp+'Z').toLocaleString())}</td><td>${escapeHTML(row.camera_id)}<small>${escapeHTML(row.zone)}</small></td><td><span class="badge ${row.access_granted?'':'warning'}">${row.access_granted?'Granted':'Denied'}</span></td></tr>`)):empty('A quiet moment','Access activity will appear here as recognition events arrive.')}</section>`;}
 } else if(!token){content=heading(titles[page],'Your security workspace, all in one place.')+signInPanel();}
 else if(['users','biometrics','permissions','settings'].includes(page)&&!admin()){content=heading(titles[page],'Workspace administration')+`<section class="panel">${empty('Administrator access required','Your account can view the dashboard and camera inventory. Contact your administrator to manage settings.')}</section>`;}
 else if(page==='cameras'){
   const rows=await api('/cameras');content=heading('Every camera. One view.','Manage the devices watching over your spaces.',admin()?'<div class="toolbar"><button class="button" data-action="discover">⌕ Discover devices</button><button class="button primary" data-action="new-camera">＋ Add camera</button></div>':'');
   content+='<div class="toolbar"><button class="button" data-action="browser-camera">Use this device’s camera</button></div>';
   content+='<div class="notice">Discover cameras attached to the server or on its local network. Test & preview captures one frame on demand; it does not record or continuously monitor video.</div>';
   content+='<div class="toolbar"><input class="search" type="search" placeholder="Search cameras or zones…" aria-label="Search cameras" id="search"></div>';
   content+=rows.length?`<div class="camera-grid">${rows.map(c=>`<article class="panel camera-card" data-search="${escapeHTML(c.name+' '+c.zone)}"><div class="camera-preview live-preview"><canvas class="camera-feed" data-feed="${c.id}" aria-label="Live view of ${escapeHTML(c.name)}"></canvas><span class="feed-placeholder">▣<br>${c.enabled?(admin()?'Connecting…':'Administrator preview required'):'Camera disabled'}</span></div><p class="feed-status" data-feed-status="${c.id}">${c.enabled&&admin()?'Waiting for first frame…':''}</p><h3>${escapeHTML(c.name)}</h3><p class="sub">${escapeHTML(c.zone)} · ${escapeHTML(c.detection)} detection</p><span class="badge ${c.enabled?'warning':'neutral'}">${c.enabled?'Enabled':'Disabled'}</span>${admin()?`<div class="record-controls"><button class="button primary" data-record="${c.id}" ${c.enabled?'':'disabled'}>● Record</button><button class="button" data-pause-recording="${c.id}" disabled>Pause</button><button class="button" data-stop-recording="${c.id}" disabled>Stop</button></div><div class="recording-result" data-recording-result="${c.id}"></div><button class="button biometric-button" data-enroll-camera="${c.id}" ${c.enabled?'':'disabled'}>◎ Add biometric data</button><button class="button" data-camera="${c.id}">Configure camera ↗</button><button class="button" data-preview="${c.id}" ${c.enabled?'':'disabled'}>Test snapshot</button>`:''}</article>`).join('')}</div>`:`<section class="panel">${empty('Make your first connection','Add a camera to organize your devices and detection settings.')}</section>`;
   window.cameraRows=rows;
 }else if(page==='biometrics'){
   content=heading('Add biometric data','Enroll a person so the recognition service can identify them.');
   content+='<div class="notice">Biometric enrollment requires the person’s explicit consent. Raw photos are processed to create an encrypted facial template and are not stored.</div>';
   content+=`<section class="panel enrollment-panel"><form id="enrollment-form"><div class="form-grid">${field('employee_id','Person ID','','text','maxlength="50" placeholder="EMP-001"')}${field('full_name','Full name','','text','maxlength="255"')}${field('department','Department','','text','maxlength="100" placeholder="Optional"')}${field('authorized_zones','Authorized zones','','text','maxlength="500" placeholder="Entrance, Office (blank means all)"')}</div><label for="field-images">Face photos</label><input id="field-images" name="images" type="file" accept="image/jpeg,image/png" multiple required><p class="sub">Select 3 to 5 clear photos of the same person: front, slight left, and slight right. Each image must contain exactly one face and be no larger than 8 MB.</p>${check('consent_given','The person gave explicit consent to process and store their encrypted biometric template',false)}<p id="enrollment-error" class="error" role="alert"></p><p id="enrollment-success" class="success" role="status"></p><button class="button primary" type="submit" id="enroll-button">Save biometric profile</button></form></section>`;
 }else if(page==='users'){
   const rows=await api('/users');window.userRows=rows;content=heading('Your people, connected.','Manage accounts and roles across your security team.','<button class="button primary" data-action="new-user">＋ Add user</button>')+'<input class="search" id="search" type="search" placeholder="Search people…" aria-label="Search users">';
   content+=`<section class="panel">${table(['Team member','Username','Role','Status',''],rows.map(u=>`<tr data-search="${escapeHTML(u.full_name+' '+u.email+' '+u.username)}"><td>${escapeHTML(u.full_name)}<small>${escapeHTML(u.email)}</small></td><td>${escapeHTML(u.username)}</td><td>${escapeHTML(u.role)}</td><td><span class="badge ${u.is_active?'':'neutral'}">${u.is_active?'Active':'Inactive'}</span></td><td><button class="button" data-user="${u.id}" aria-label="Configure ${escapeHTML(u.full_name)}">Configure ↗</button></td></tr>`))}</section>`;
 }else if(page==='permissions'){
   const rows=await api('/permissions');window.personRows=rows;content=heading('Access with intention.','Set zone permissions for enrolled biometric profiles.');content+='<div class="notice">System roles are managed under Users. Biometric profiles are enrolled through the access API with explicit consent.</div>';
   content+=`<section class="panel">${rows.length?table(['Person','Authorized zones','Access',''],rows.map(p=>`<tr><td>${escapeHTML(p.full_name)}<small>${escapeHTML(p.employee_id)} · ${escapeHTML(p.department)}</small></td><td>${escapeHTML(p.authorized_zones||'All zones')}</td><td><span class="badge ${p.is_active?'':'neutral'}">${p.is_active?'Enabled':'Disabled'}</span></td><td><button class="button" data-person="${p.id}">Edit permissions ↗</button></td></tr>`)):empty('No enrolled profiles yet','Enroll a person with biometric consent to manage their zone access.','<br><a class="button" href="#biometrics">Add biometric data ↗</a>')}</section>`;
 }else{content=heading('Make the workspace yours.','Configure devices, accounts, and access from one place.')+modules()+`<section class="panel"><h2>Device connections</h2><p class="sub">Discover local USB capture devices, ONVIF cameras on the server network, or connected Bluetooth devices. A Bluetooth device needs a compatible video driver or Wi-Fi stream to supply video.</p><button class="button primary" data-action="discover">Discover devices</button><a class="button" href="#cameras">Configure cameras ↗</a></section><section class="panel"><h2>Account settings</h2><p class="sub">Signed in as ${escapeHTML(currentUser.email)}. Update names, email addresses, roles, and account status from Users.</p><a class="button" href="#users">Configure users ↗</a></section>`;}
 if(version===generation){main.innerHTML=content;if(page==='cameras'&&admin())startCameraFeeds(window.cameraRows.filter(camera=>camera.enabled));if(page==='biometrics'&&admin())setupEnrollmentForm();}
 }catch(error){if(version===generation)main.innerHTML=heading(titles[page],'Workspace')+`<section class="panel">${empty('We couldn’t load this page',escapeHTML(error.message),'<br><button class="button" data-action="retry">Try again</button>')}</section>`;}
}
function startCameraFeeds(cameras){cameras.forEach(camera=>{const feed={stopped:false,controller:new AbortController()};cameraFeeds.set(camera.id,feed);streamCameraFeed(camera.id);});}
async function streamCameraFeed(id){
 const feed=cameraFeeds.get(id),canvas=document.querySelector(`[data-feed="${id}"]`),status=document.querySelector(`[data-feed-status="${id}"]`);if(!feed||feed.stopped||!canvas)return;
 try{const response=await fetch('/api/cameras/'+id+'/stream',{headers:{Authorization:'Bearer '+token},signal:feed.controller.signal});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.detail||'Camera stream unavailable');}const reader=response.body.getReader();let buffer=new Uint8Array(0);
 while(!feed.stopped){const {done,value}=await reader.read();if(done)break;const merged=new Uint8Array(buffer.length+value.length);merged.set(buffer);merged.set(value,buffer.length);buffer=merged;while(buffer.length>=4){const size=new DataView(buffer.buffer,buffer.byteOffset,4).getUint32(0);if(size<2||size>4*1024*1024)throw new Error('Invalid camera frame');if(buffer.length<4+size)break;const jpeg=buffer.slice(4,4+size);buffer=buffer.slice(4+size);const bitmap=await createImageBitmap(new Blob([jpeg],{type:'image/jpeg'}));if(feed.stopped||!canvas.isConnected){bitmap.close();return;}canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();canvas.parentElement.classList.add('has-frame');const recorder=cameraRecordings.get(id)?.recorder;status.textContent=recorder?.state==='recording'?'Recording…':recorder?.state==='paused'?'Recording paused':'Live · '+new Date().toLocaleTimeString();}}
 if(!feed.stopped)throw new Error('Camera disconnected');
 }catch(error){if(error.name!=='AbortError'&&status?.isConnected)status.textContent=error.message;}
}
function recordingButtons(id,isRecording,isPaused=false){const start=document.querySelector(`[data-record="${id}"]`),pause=document.querySelector(`[data-pause-recording="${id}"]`),stop=document.querySelector(`[data-stop-recording="${id}"]`);if(!start)return;start.disabled=isRecording;pause.disabled=!isRecording;pause.textContent=isPaused?'Resume':'Pause';stop.disabled=!isRecording;}
function startCameraRecording(id){
 const canvas=document.querySelector(`[data-feed="${id}"]`),status=document.querySelector(`[data-feed-status="${id}"]`);if(!canvas?.width){toast('Wait until the camera displays its first frame');return;}if(!window.MediaRecorder||!canvas.captureStream){toast('This browser does not support camera recording');return;}
 const stream=canvas.captureStream(10),mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(type=>MediaRecorder.isTypeSupported(type))||'',chunks=[],recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined),recording={recorder,stream,chunks,url:null};cameraRecordings.set(id,recording);
 recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=()=>finishCameraRecording(id);recorder.start(1000);recordingButtons(id,true);status.textContent='Recording…';
}
function pauseCameraRecording(id){const recording=cameraRecordings.get(id);if(!recording||recording.recorder.state==='inactive')return;const pause=recording.recorder.state==='recording';pause?recording.recorder.pause():recording.recorder.resume();recordingButtons(id,true,pause);const status=document.querySelector(`[data-feed-status="${id}"]`);if(status)status.textContent=pause?'Recording paused':'Recording…';}
function stopCameraRecording(id){const recording=cameraRecordings.get(id);if(recording?.recorder.state!=='inactive')recording.recorder.stop();}
function finishCameraRecording(id){const recording=cameraRecordings.get(id),result=document.querySelector(`[data-recording-result="${id}"]`);if(!recording)return;recording.stream.getTracks().forEach(track=>track.stop());recording.url=URL.createObjectURL(new Blob(recording.chunks,{type:recording.recorder.mimeType||'video/webm'}));recordingButtons(id,false);if(result)result.innerHTML=`<video controls src="${recording.url}" class="recorded-video"></video><div class="record-actions"><a class="button" href="${recording.url}" download="camera-${id}-${Date.now()}.webm">Download video</a><button class="button danger" data-delete-recording="${id}">Delete video</button></div>`;}
function deleteCameraRecording(id){const recording=cameraRecordings.get(id);if(!recording)return;if(recording.recorder.state!=='inactive')recording.recorder.stop();if(recording.url)URL.revokeObjectURL(recording.url);recording.stream?.getTracks().forEach(track=>track.stop());cameraRecordings.delete(id);const result=document.querySelector(`[data-recording-result="${id}"]`);if(result)result.innerHTML='';recordingButtons(id,false);toast('Video deleted');}
function table(headings,rows){return `<div class="table-wrap"><table><thead><tr>${headings.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function setupEnrollmentForm(){
 const form=$('#enrollment-form');if(!form)return;form.onsubmit=async event=>{event.preventDefault();const error=$('#enrollment-error'),success=$('#enrollment-success'),button=$('#enroll-button'),files=form.elements.images.files;error.textContent='';success.textContent='';
 if(files.length<3||files.length>5){error.textContent='Select between 3 and 5 face photos.';return;}if([...files].some(file=>!['image/jpeg','image/png'].includes(file.type)||file.size>8*1024*1024)){error.textContent='Every photo must be JPEG or PNG and no larger than 8 MB.';return;}if(!form.elements.consent_given.checked){error.textContent='Explicit biometric consent is required.';return;}
 button.disabled=true;button.textContent='Creating encrypted template…';try{const person=await api('/access/enroll',{method:'POST',body:new FormData(form)});form.reset();success.textContent=`${person.full_name} was enrolled successfully. Recognition is now enabled for this profile.`;toast('Biometric profile saved');}catch(reason){error.textContent=reason.message;}finally{button.disabled=false;button.textContent='Save biometric profile';}};
}
function cameraEnrollment(id){
 clearEnrollmentPhotos();enrollmentCameraId=id;
 $('#dialog-title').textContent='Add biometric data';$('#form-error').textContent='';$('#save-button').hidden=false;$('#save-button').textContent='Save biometric profile';
 $('#fields').innerHTML='<p class="sub">Capture 3 to 5 photos from this camera. Ask the person to look forward, slightly left, and slightly right.</p>'+field('employee_id','Person ID','','text','maxlength="50" placeholder="EMP-001"')+field('full_name','Full name','','text','maxlength="255"')+field('department','Department','','text','maxlength="100" placeholder="Optional"')+field('authorized_zones','Authorized zones','','text','maxlength="500" placeholder="Entrance, Office (blank means all)"')+check('consent_given','The person gave explicit consent for biometric processing',false)+'<button type="button" class="button capture-biometric" data-capture-biometric="'+id+'">Capture photo</button><p id="capture-status" class="sub" role="status">0 of 3 minimum photos captured.</p><div id="biometric-thumbnails" class="biometric-thumbnails"></div>';
 $('#editor').onsubmit=async event=>{event.preventDefault();const button=$('#save-button');$('#form-error').textContent='';if(enrollmentPhotos.length<3){$('#form-error').textContent='Capture at least 3 photos.';return;}const form=new FormData(event.target);enrollmentPhotos.forEach((photo,index)=>form.append('images',photo.blob,`camera-${id}-${index+1}.jpg`));button.disabled=true;button.textContent='Creating encrypted template…';try{const person=await api('/access/enroll',{method:'POST',body:form});$('#modal').close();toast(`${person.full_name} was enrolled successfully`);await render();}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;button.textContent='Save biometric profile';}};$('#modal').showModal();
}
async function captureBiometricPhoto(id){
 const status=$('#capture-status'),button=document.querySelector('[data-capture-biometric]');if(enrollmentPhotos.length>=5){status.textContent='Maximum of 5 photos reached.';return;}button.disabled=true;status.textContent='Capturing photo…';
 try{const response=await fetch('/api/cameras/'+id+'/snapshot',{method:'POST',headers:{Authorization:'Bearer '+token}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.detail||'Could not capture a frame');}const blob=await response.blob(),url=URL.createObjectURL(blob);enrollmentPhotos.push({blob,url});$('#biometric-thumbnails').innerHTML=enrollmentPhotos.map((photo,index)=>`<figure><img src="${photo.url}" alt="Biometric capture ${index+1}"><button type="button" class="icon-button" data-remove-biometric="${index}" aria-label="Remove photo ${index+1}">×</button></figure>`).join('');status.textContent=`${enrollmentPhotos.length} of 3 minimum photos captured.${enrollmentPhotos.length>=3?' Ready to save.':''}`;
 }catch(error){status.textContent=error.message;}finally{button.disabled=enrollmentPhotos.length>=5;}
}
function removeBiometricPhoto(index){const photo=enrollmentPhotos.splice(index,1)[0];if(photo)URL.revokeObjectURL(photo.url);const container=$('#biometric-thumbnails');if(container)container.innerHTML=enrollmentPhotos.map((item,position)=>`<figure><img src="${item.url}" alt="Biometric capture ${position+1}"><button type="button" class="icon-button" data-remove-biometric="${position}" aria-label="Remove photo ${position+1}">×</button></figure>`).join('');const status=$('#capture-status');if(status)status.textContent=`${enrollmentPhotos.length} of 3 minimum photos captured.`;const button=document.querySelector('[data-capture-biometric]');if(button)button.disabled=false;}
function field(name,label,value='',type='text',extra=''){return `<label for="field-${name}">${label}</label><input id="field-${name}" name="${name}" type="${type}" value="${escapeHTML(value)}" required ${extra}>`;}
function select(name,label,values,value){return `<label for="field-${name}">${label}</label><select id="field-${name}" name="${name}">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('')}</select>`;}
function check(name,label,value){return `<label class="check"><input name="${name}" type="checkbox" ${value?'checked':''}>${label}</label>`;}
function dialog(title,fields,save,label='Save changes'){
 clearPreview();$('#save-button').hidden=false;$('#dialog-title').textContent=title;$('#fields').innerHTML=fields;$('#form-error').textContent='';$('#save-button').textContent=label;$('#modal').showModal();
 $('#editor').onsubmit=async event=>{event.preventDefault();const button=$('#save-button');button.disabled=true;$('#form-error').textContent='';try{await save(new FormData(event.target));$('#modal').close();toast(title==='Sign in'?'Welcome to your workspace':'Changes saved');await render();}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;}};
}
function login(){dialog('Sign in','<p class="sub">Welcome back. Use your workspace account.</p>'+field('username','Email address','','email','autocomplete="username"')+field('password','Password','','password','autocomplete="current-password"'),async form=>{const result=await api('/auth/login',{method:'POST',body:new URLSearchParams(form)});token=result.access_token;sessionStorage.setItem('sentinel-token',token);currentUser=await api('/auth/me');updateSession();},'Sign in →');}
function cameraEditor(c){dialog(c?.id?'Configure camera':'Add camera',field('name','Camera name',c?.name,'text','maxlength="100"')+field('zone','Zone',c?.zone,'text','maxlength="100"')+field('source','Video source',c?.source,'text','placeholder="/dev/video0 or rtsp://192.168.1.10/stream" maxlength="500"')+'<p class="sub">Local: /dev/videoN. Network: RTSP stream or HTTP JPEG snapshot URL, using a private IP without embedded credentials. Network capture requires that IP in the server CAMERA_ALLOWED_HOSTS setting. An ONVIF service URL is not a video URL.</p>'+select('detection','Detection mode',['both','face','animal'],c?.detection||'both')+'<p class="sub">Detection mode is saved for the recognition integration; preview only checks video capture.</p>'+check('enabled','Enable camera',c?.enabled??true)+(c?.id?'<button type="button" class="button danger" data-remove="'+c.id+'">Remove camera</button>':''),form=>api('/cameras'+(c?.id?'/'+c.id:''),{method:c?.id?'PUT':'POST',body:JSON.stringify({...Object.fromEntries(form),enabled:form.has('enabled')})}));}
function discoveryPanel(){
 discoveryRows=[];$('#dialog-title').textContent='Discover camera devices';$('#form-error').textContent='';$('#save-button').hidden=true;
 $('#fields').innerHTML='<p class="sub">Discovery runs on the Python server, not on the computer displaying this page.</p><div class="discovery-tabs"><button type="button" class="button" data-discover="usb">USB / local</button><button type="button" class="button" data-discover="network">Wi-Fi / network</button><button type="button" class="button" data-discover="bluetooth">Bluetooth</button></div><div id="discovery-results" role="status" aria-live="polite">Choose a connection type to search.</div>';
 $('#editor').onsubmit=event=>event.preventDefault();$('#modal').showModal();
}
async function discoverDevices(transport){
 const results=$('#discovery-results');if(!results)return;
 document.querySelectorAll('[data-discover]').forEach(button=>button.disabled=true);
 results.textContent='Looking for devices…';
 try{const data=await api('/cameras/discovery/'+transport,{method:'POST'});if(!results.isConnected)return;
 discoveryRows=data.devices;results.innerHTML='<p class="sub">'+escapeHTML(data.message)+'</p>'+data.devices.map((device,index)=>'<article class="discovered-device"><strong>'+escapeHTML(device.name)+'</strong><p class="sub">'+escapeHTML(device.source||device.address)+' · '+escapeHTML(device.status.replaceAll('_',' '))+'</p>'+(device.can_register?'<button type="button" class="button" data-register="'+index+'">'+(device.transport==='network'?'Set stream URL':'Add camera')+'</button>':'<span class="badge warning">Video driver required</span>')+'</article>').join('')+(!data.devices.length?'<p class="sub">No devices found. Check the connection and server permissions, then try again.</p>':'');
 }catch(error){if(results.isConnected)results.textContent=error.message;}
 finally{document.querySelectorAll('[data-discover]').forEach(button=>button.disabled=false);}
}
async function previewCamera(id){
 clearPreview();$('#dialog-title').textContent='Camera connection test';$('#form-error').textContent='';$('#save-button').hidden=true;$('#fields').innerHTML='<p id="preview-status" class="sub" role="status">Opening camera… (up to 8 seconds)</p><div id="preview-image"></div>';$('#editor').onsubmit=event=>event.preventDefault();$('#modal').showModal();
 const status=$('#preview-status');const authToken=token;
 try{const response=await fetch('/api/cameras/'+id+'/snapshot',{method:'POST',headers:{Authorization:'Bearer '+authToken}});
 if(!response.ok){const error=await response.json();throw new Error(error.detail||'Camera test failed');}
 const blob=await response.blob();if(!status.isConnected||!$('#modal').open||token!==authToken)return;
 previewURL=URL.createObjectURL(blob);const img=document.createElement('img');img.src=previewURL;img.alt='Camera test snapshot';img.className='snapshot';$('#preview-image').append(img);status.textContent='Frame received at '+new Date().toLocaleTimeString()+'. This is a snapshot, not a live stream.';
 }catch(error){if(status.isConnected)status.textContent=error.message;}
}
function browserCamera(){
 clearPreview();$('#dialog-title').textContent='This device’s camera';$('#form-error').textContent='';$('#save-button').hidden=true;
 $('#fields').innerHTML='<p class="sub">Preview the camera on the laptop or phone running this browser. Video stays in this browser and is not recorded or sent to the server. To view a phone camera remotely, configure its Wi-Fi stream under Cameras.</p><p id="browser-status" class="sub" role="status"></p><label for="browser-device">Camera</label><select id="browser-device" aria-label="Select camera" disabled><option>Detecting cameras…</option></select><video id="browser-video" class="snapshot" autoplay muted playsinline></video>';
 $('#editor').onsubmit=event=>event.preventDefault();$('#modal').showModal();
 $('#browser-device').onchange=event=>startBrowserCamera(event.target.value);startBrowserCamera();
}
async function startBrowserCamera(deviceId){
 const request=++browserRequest;stopBrowserStream();const status=$('#browser-status'),selector=$('#browser-device');
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){status.textContent='Browser camera access requires HTTPS, or localhost on this device. Use a trusted HTTPS address when opening this workspace on a phone.';return;}
 selector.disabled=true;status.textContent=deviceId?'Switching camera…':'Waiting for camera permission…';
 try{
 const stream=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'}},audio:false});
 if(request!==browserRequest||!status.isConnected||!$('#modal').open){stream.getTracks().forEach(track=>track.stop());return;}
 browserStream=stream;const video=$('#browser-video');video.srcObject=stream;await video.play();
 const devices=await navigator.mediaDevices.enumerateDevices();if(request!==browserRequest||!status.isConnected)return;
 const selected=stream.getVideoTracks()[0].getSettings().deviceId,videoInputs=devices.filter(device=>device.kind==='videoinput');
 selector.innerHTML=videoInputs.map((device,index)=>'<option value="'+escapeHTML(device.deviceId)+'" '+(device.deviceId===selected?'selected':'')+'>'+escapeHTML(device.label||'Camera '+(index+1))+'</option>').join('');selector.disabled=videoInputs.length<2;
 status.textContent='Camera connected. Close this dialog to stop the camera.';
 stream.getVideoTracks()[0].onended=()=>{if(request===browserRequest&&status.isConnected)status.textContent='Camera disconnected or permission revoked. Close and reopen to reconnect.';};
 }catch(error){if(request===browserRequest&&status.isConnected){stopBrowserStream();selector.disabled=false;status.textContent=error.name==='NotAllowedError'?'Camera permission denied. Allow access in your browser settings and try again.':error.name==='NotFoundError'||error.name==='OverconstrainedError'?'The selected camera is no longer available. Choose another camera or reconnect it.':'Could not open the camera. Close other apps using it and try again.';}}
}
function removeCamera(id){dialog('Remove camera','<p class="sub">Remove this camera configuration? Existing access logs will be preserved.</p>',()=>api('/cameras/'+id,{method:'DELETE'}),'Remove camera');}

function userEditor(u){dialog(u?'Configure user':'Add user',field('full_name','Full name',u?.full_name,'text','maxlength="255"')+field('email','Email',u?.email,'email')+(!u?field('username','Username','','text','minlength="3" maxlength="100"')+field('password','Password','','password','minlength="12" maxlength="128" autocomplete="new-password"'):'')+select('role','System role',['security','user','admin'],u?.role||'security')+(u?check('is_active','Account active',u.is_active):''),form=>api('/users'+(u?'/'+u.id:''),{method:u?'PUT':'POST',body:JSON.stringify({...Object.fromEntries(form),...(u?{is_active:form.has('is_active')}:{})})}));}
function permissionEditor(p){dialog('Edit permissions',`<p class="sub">${escapeHTML(p.full_name)} · ${escapeHTML(p.employee_id)}</p><label for="zones">Authorized zones</label><input id="zones" name="authorized_zones" maxlength="500" value="${escapeHTML(p.authorized_zones)}" placeholder="Reception, Office"><p class="sub">Separate exact zone names with commas. Leaving this blank grants access to all zones.</p>`+check('is_active','Allow biometric access',p.is_active),form=>api('/permissions/'+p.id,{method:'PUT',body:JSON.stringify({authorized_zones:form.get('authorized_zones'),is_active:form.has('is_active')})}));}
$('#close-modal').onclick=()=>$('#modal').close();
$('#modal').addEventListener('close',()=>{clearPreview();clearEnrollmentPhotos();enrollmentCameraId=null;$('#save-button').hidden=false;});
$('#session-button').onclick=()=>{if(!token)return login();token=null;currentUser=null;sessionStorage.removeItem('sentinel-token');updateSession();render();};
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const action=button.dataset.action;if(action==='browser-camera')browserCamera();if(action==='discover')discoveryPanel();if(action==='login')login();if(action==='retry')render();if(action==='new-camera')cameraEditor();if(action==='new-user')userEditor();if(button.dataset.discover)discoverDevices(button.dataset.discover);if(button.dataset.preview)previewCamera(Number(button.dataset.preview));if(button.dataset.record)startCameraRecording(Number(button.dataset.record));if(button.dataset.pauseRecording)pauseCameraRecording(Number(button.dataset.pauseRecording));if(button.dataset.stopRecording)stopCameraRecording(Number(button.dataset.stopRecording));if(button.dataset.deleteRecording)deleteCameraRecording(Number(button.dataset.deleteRecording));if(button.dataset.enrollCamera)cameraEnrollment(Number(button.dataset.enrollCamera));if(button.dataset.captureBiometric)captureBiometricPhoto(Number(button.dataset.captureBiometric));if(button.dataset.removeBiometric!==undefined)removeBiometricPhoto(Number(button.dataset.removeBiometric));if(button.dataset.remove)removeCamera(Number(button.dataset.remove));if(button.dataset.register!==undefined){const device=discoveryRows[Number(button.dataset.register)];cameraEditor({name:device.name,source:device.source,zone:''});}if(button.dataset.camera)cameraEditor(window.cameraRows.find(c=>c.id===Number(button.dataset.camera)));if(button.dataset.user)userEditor(window.userRows.find(u=>u.id===Number(button.dataset.user)));if(button.dataset.person)permissionEditor(window.personRows.find(p=>p.id===Number(button.dataset.person)));});
document.addEventListener('input',event=>{if(event.target.id==='search'){const query=event.target.value.toLowerCase();document.querySelectorAll('[data-search]').forEach(row=>row.hidden=!row.dataset.search.toLowerCase().includes(query));}});
window.addEventListener('hashchange',render);
window.addEventListener('pagehide',()=>{clearPreview();clearCameraFeeds();});
(async()=>{if(token){try{currentUser=await api('/auth/me');}catch{token=null;sessionStorage.removeItem('sentinel-token');}}updateSession();render();})();
