'use strict';
const $ = s => document.querySelector(s);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token = sessionStorage.getItem('sentinel-token'), currentUser = null, generation = 0;
const titles = {home:'Overview',dashboard:'Dashboard',cameras:'Cameras',permissions:'Permissions',users:'Users',settings:'Configuration'};
const admin = () => currentUser?.role === 'admin';
async function api(path, options = {}) {
  const response = await fetch('/api' + path, {...options, headers:{...(token ? {Authorization:'Bearer ' + token}:{}), ...(options.body instanceof URLSearchParams ? {} : {'Content-Type':'application/json'}), ...options.headers}});
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    if(response.status === 401 && !path.startsWith('/auth/login')) {token=null;currentUser=null;sessionStorage.removeItem('sentinel-token');updateSession();}
    throw new Error(Array.isArray(data.detail) ? data.detail.map(x => x.msg).join('; ') : data.detail || 'Unable to connect. Please try again.');
  }
  return data;
}
function updateSession(){ $('#session-status').textContent=currentUser ? `${currentUser.full_name || currentUser.username} · ${currentUser.role}` : 'Guest workspace';$('#session-button').textContent=currentUser ? '↪' : '↗';$('#session-button').setAttribute('aria-label',currentUser?'Sign out':'Sign in');}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500);}
function heading(title, description, action=''){return `<div class="page-heading"><div><span class="eyebrow">YOUR SECURITY WORKSPACE</span><h1>${title}</h1><p class="sub">${description}</p></div>${action || `<span class="date">${new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date())}</span>`}</div>`;}
function empty(title,detail,action=''){return `<div class="empty"><strong>${title}</strong>${detail}${action}</div>`;}
function signInPanel(){return `<section class="panel">${empty('Your workspace is ready','Sign in to view live metrics and manage your connected spaces.','<br><button class="button primary" data-action="login">Sign in to workspace ↗</button>')}</section>`;}
function stats(summary,cameras){return `<div class="stats">${[['Registered cameras',cameras?.length,'Configured devices','▣'],['Authorized people',summary?.authorized_people,'Active biometric profiles','♧'],['Access attempts',summary?.access_attempts_24h,'In the last 24 hours','⇥'],['Open alerts',summary?.unresolved_alerts,'Awaiting review','◇']].map(([label,value,note,icon])=>`<article class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><div class="stat-value">${value ?? '—'}</div><span class="stat-note">${note}</span></article>`).join('')}</div>`;}
function modules(){return `<div class="section-head"><h2>A little control. A lot of confidence.</h2><span>Your workspace, connected</span></div><div class="modules">${[['cameras','▣','Keep an eye on every space','View your camera inventory and configure detection for each location.','Manage cameras'],['permissions','◇','The right access, for everyone','Manage biometric access and decide who can enter each zone.','Manage permissions'],['users','♧','People at the heart of security','View your team, configure accounts, and manage system roles.','Manage users']].map(([page,icon,title,description,link])=>`<a class="module" href="#${page}"><span class="module-icon">${icon}</span><h3>${title}</h3><p>${description}</p><span class="module-link">${link}<span>↗</span></span></a>`).join('')}</div>`;}
async function render(){
 const version=++generation;const page=titles[location.hash.slice(1)] ? location.hash.slice(1) : 'home';
 $('#breadcrumb').textContent=titles[page];document.title=`${titles[page]} · Sentinel`;
 document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const main=$('#main');main.innerHTML='<div class="loading">Loading your workspace…</div>';
 try{
 let content='';
 if(page==='home'||page==='dashboard'){
   const [summary,cameras]=token?await Promise.all([api('/dashboard/summary'),api('/cameras')]):[null,null];
   content=heading(page==='home'?'Everything in sight. Everything in control.':'A clearer view of your security.',page==='home'?'Welcome to Sentinel. A calmer way to manage access to your spaces.':'Live access metrics from the last 24 hours.');
   if(page==='home')content+=`<section class="hero"><div><span class="eyebrow">CONNECTED SPACES. CONFIDENT DECISIONS.</span><h2>Security starts with<br>a complete picture.</h2><p>Bring your cameras, people, and access permissions together in one simple workspace.</p><a class="button" href="#dashboard">Open dashboard <span>↗</span></a></div><div class="radar" aria-hidden="true"><div class="shield">✓</div></div></section>`;
   content+=stats(summary,cameras);
   if(page==='home')content+=modules();
   if(page==='dashboard'&&summary){const total=summary.access_attempts_24h;content+=`<section class="panel"><div class="panel-head"><h2>Access at a glance</h2><span class="badge">Last 24 hours</span></div><div class="meter-row">${[['Granted',summary.granted_24h],['Denied',summary.denied_24h]].map(([label,value])=>{let percent=total?Math.round(value/total*100):0;return `<div class="meter"><div class="meter-circle" style="--value:${percent}"><span>${total?percent+'%':'—'}</span></div><h2>${label}</h2><p>${value} of ${total} attempts</p></div>`;}).join('')}<div class="meter"><div class="meter-circle"><span>${summary.unresolved_alerts}</span></div><h2>Open alerts</h2><p>Unresolved security events</p></div></div></section>`;}
   if(!token)content+=signInPanel();
   else if(admin()){const logs=await api('/logs/access?limit=6');content+=`<section class="panel"><div class="panel-head"><h2>Recent activity</h2><span class="badge neutral">Latest access events</span></div>${logs.length?table(['Time','Camera / zone','Result'],logs.map(row=>`<tr><td>${escapeHTML(new Date(row.timestamp+'Z').toLocaleString())}</td><td>${escapeHTML(row.camera_id)}<small>${escapeHTML(row.zone)}</small></td><td><span class="badge ${row.access_granted?'':'warning'}">${row.access_granted?'Granted':'Denied'}</span></td></tr>`)):empty('A quiet moment','Access activity will appear here as recognition events arrive.')}</section>`;}
 } else if(!token){content=heading(titles[page],'Your security workspace, all in one place.')+signInPanel();}
 else if(['users','permissions','settings'].includes(page)&&!admin()){content=heading(titles[page],'Workspace administration')+`<section class="panel">${empty('Administrator access required','Your account can view the dashboard and camera inventory. Contact your administrator to manage settings.')}</section>`;}
 else if(page==='cameras'){
   const rows=await api('/cameras');content=heading('Every camera. One view.','Manage the devices watching over your spaces.',admin()?'<button class="button primary" data-action="new-camera">＋ Add camera</button>':'');
   content+='<div class="notice">Camera inventory · Live streams and connection telemetry are not connected yet.</div>';
   content+='<div class="toolbar"><input class="search" type="search" placeholder="Search cameras or zones…" aria-label="Search cameras" id="search"></div>';
   content+=rows.length?`<div class="camera-grid">${rows.map(c=>`<article class="panel camera-card" data-search="${escapeHTML(c.name+' '+c.zone)}"><div class="camera-preview"><span>▣</span>Live preview unavailable</div><h3>${escapeHTML(c.name)}</h3><p class="sub">${escapeHTML(c.zone)} · ${escapeHTML(c.detection)} detection</p><span class="badge ${c.enabled?'warning':'neutral'}">${c.enabled?'Connection unverified':'Disabled'}</span>${admin()?`<button class="button" data-camera="${c.id}">Configure camera ↗</button>`:''}</article>`).join('')}</div>`:`<section class="panel">${empty('Make your first connection','Add a camera to organize your devices and detection settings.')}</section>`;
   window.cameraRows=rows;
 }else if(page==='users'){
   const rows=await api('/users');window.userRows=rows;content=heading('Your people, connected.','Manage accounts and roles across your security team.','<button class="button primary" data-action="new-user">＋ Add user</button>')+'<input class="search" id="search" type="search" placeholder="Search people…" aria-label="Search users">';
   content+=`<section class="panel">${table(['Team member','Username','Role','Status',''],rows.map(u=>`<tr data-search="${escapeHTML(u.full_name+' '+u.email+' '+u.username)}"><td>${escapeHTML(u.full_name)}<small>${escapeHTML(u.email)}</small></td><td>${escapeHTML(u.username)}</td><td>${escapeHTML(u.role)}</td><td><span class="badge ${u.is_active?'':'neutral'}">${u.is_active?'Active':'Inactive'}</span></td><td><button class="button" data-user="${u.id}" aria-label="Configure ${escapeHTML(u.full_name)}">Configure ↗</button></td></tr>`))}</section>`;
 }else if(page==='permissions'){
   const rows=await api('/permissions');window.personRows=rows;content=heading('Access with intention.','Set zone permissions for enrolled biometric profiles.');content+='<div class="notice">System roles are managed under Users. Biometric profiles are enrolled through the access API with explicit consent.</div>';
   content+=`<section class="panel">${rows.length?table(['Person','Authorized zones','Access',''],rows.map(p=>`<tr><td>${escapeHTML(p.full_name)}<small>${escapeHTML(p.employee_id)} · ${escapeHTML(p.department)}</small></td><td>${escapeHTML(p.authorized_zones||'All zones')}</td><td><span class="badge ${p.is_active?'':'neutral'}">${p.is_active?'Enabled':'Disabled'}</span></td><td><button class="button" data-person="${p.id}">Edit permissions ↗</button></td></tr>`)):empty('No enrolled profiles yet','Enroll a person with biometric consent to manage their zone access.','<br><a class="button" href="/docs#/Control%20de%20Acceso">Open enrollment API ↗</a>')}</section>`;
 }else{content=heading('Make the workspace yours.','Configure devices, accounts, and access from one place.')+modules()+`<section class="panel"><h2>Account settings</h2><p class="sub">Signed in as ${escapeHTML(currentUser.email)}. Update names, email addresses, roles, and account status from Users.</p><a class="button" href="#users">Configure users ↗</a></section>`;}
 if(version===generation)main.innerHTML=content;
 }catch(error){if(version===generation)main.innerHTML=heading(titles[page],'Workspace')+`<section class="panel">${empty('We couldn’t load this page',escapeHTML(error.message),'<br><button class="button" data-action="retry">Try again</button>')}</section>`;}
}
function table(headings,rows){return `<div class="table-wrap"><table><thead><tr>${headings.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function field(name,label,value='',type='text',extra=''){return `<label for="field-${name}">${label}</label><input id="field-${name}" name="${name}" type="${type}" value="${escapeHTML(value)}" required ${extra}>`;}
function select(name,label,values,value){return `<label for="field-${name}">${label}</label><select id="field-${name}" name="${name}">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('')}</select>`;}
function check(name,label,value){return `<label class="check"><input name="${name}" type="checkbox" ${value?'checked':''}>${label}</label>`;}
function dialog(title,fields,save,label='Save changes'){
 $('#dialog-title').textContent=title;$('#fields').innerHTML=fields;$('#form-error').textContent='';$('#save-button').textContent=label;$('#modal').showModal();
 $('#editor').onsubmit=async event=>{event.preventDefault();const button=$('#save-button');button.disabled=true;$('#form-error').textContent='';try{await save(new FormData(event.target));$('#modal').close();toast(title==='Sign in'?'Welcome to your workspace':'Changes saved');await render();}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;}};
}
function login(){dialog('Sign in','<p class="sub">Welcome back. Use your workspace account.</p>'+field('username','Email address','','email','autocomplete="username"')+field('password','Password','','password','autocomplete="current-password"'),async form=>{const result=await api('/auth/login',{method:'POST',body:new URLSearchParams(form)});token=result.access_token;sessionStorage.setItem('sentinel-token',token);currentUser=await api('/auth/me');updateSession();},'Sign in →');}
function cameraEditor(c){dialog(c?'Configure camera':'Add camera',field('name','Camera name',c?.name,'text','maxlength="100"')+field('zone','Zone',c?.zone,'text','maxlength="100"')+field('source','Camera URL',c?.source,'text','placeholder="rtsp://192.168.1.10/stream" maxlength="500"')+'<p class="sub">Use an RTSP or HTTP URL without embedded credentials. Saving registers configuration; it does not start a stream.</p>'+select('detection','Detection mode',['both','face','animal'],c?.detection||'both')+check('enabled','Enable camera',c?.enabled??true),form=>api('/cameras'+(c?'/'+c.id:''),{method:c?'PUT':'POST',body:JSON.stringify({...Object.fromEntries(form),enabled:form.has('enabled')})}));}
function userEditor(u){dialog(u?'Configure user':'Add user',field('full_name','Full name',u?.full_name,'text','maxlength="255"')+field('email','Email',u?.email,'email')+(!u?field('username','Username','','text','minlength="3" maxlength="100"')+field('password','Password','','password','minlength="12" maxlength="128" autocomplete="new-password"'):'')+select('role','System role',['security','user','admin'],u?.role||'security')+(u?check('is_active','Account active',u.is_active):''),form=>api('/users'+(u?'/'+u.id:''),{method:u?'PUT':'POST',body:JSON.stringify({...Object.fromEntries(form),...(u?{is_active:form.has('is_active')}:{})})}));}
function permissionEditor(p){dialog('Edit permissions',`<p class="sub">${escapeHTML(p.full_name)} · ${escapeHTML(p.employee_id)}</p><label for="zones">Authorized zones</label><input id="zones" name="authorized_zones" maxlength="500" value="${escapeHTML(p.authorized_zones)}" placeholder="Reception, Office"><p class="sub">Separate exact zone names with commas. Leaving this blank grants access to all zones.</p>`+check('is_active','Allow biometric access',p.is_active),form=>api('/permissions/'+p.id,{method:'PUT',body:JSON.stringify({authorized_zones:form.get('authorized_zones'),is_active:form.has('is_active')})}));}
$('#close-modal').onclick=()=>$('#modal').close();
$('#session-button').onclick=()=>{if(!token)return login();token=null;currentUser=null;sessionStorage.removeItem('sentinel-token');updateSession();render();};
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const action=button.dataset.action;if(action==='login')login();if(action==='retry')render();if(action==='new-camera')cameraEditor();if(action==='new-user')userEditor();if(button.dataset.camera)cameraEditor(window.cameraRows.find(c=>c.id===Number(button.dataset.camera)));if(button.dataset.user)userEditor(window.userRows.find(u=>u.id===Number(button.dataset.user)));if(button.dataset.person)permissionEditor(window.personRows.find(p=>p.id===Number(button.dataset.person)));});
document.addEventListener('input',event=>{if(event.target.id==='search'){const query=event.target.value.toLowerCase();document.querySelectorAll('[data-search]').forEach(row=>row.hidden=!row.dataset.search.toLowerCase().includes(query));}});
window.addEventListener('hashchange',render);
(async()=>{if(token){try{currentUser=await api('/auth/me');}catch{token=null;sessionStorage.removeItem('sentinel-token');}}updateSession();render();})();
