'use strict';
const $ = s => document.querySelector(s);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let previewURL = null, discoveryRows = [], browserStream = null, browserRequest = 0;
const cameraFeeds=new Map(),cameraRecordings=new Map();
let enrollmentPhotos=[],enrollmentCameraId=null;
let token = sessionStorage.getItem('centinel-token'), currentUser = null, generation = 0;
const titles = {home:'Inicio',dashboard:'Panel',cameras:'Cámaras',biometrics:'Biometría',permissions:'Permisos',users:'Usuarios',settings:'Configuración'};
const valueLabels = {both:'rostros y animales',face:'rostros',animal:'animales',security:'seguridad',user:'usuario',admin:'administrador'};
const translatedValue = value => valueLabels[value] || value;
const admin = () => currentUser?.role === 'admin';
async function api(path, options = {}) {
  const formBody=options.body instanceof URLSearchParams||options.body instanceof FormData;
  const response = await fetch('/api' + path, {...options, headers:{...(token ? {Authorization:'Bearer ' + token}:{}), ...(formBody ? {} : {'Content-Type':'application/json'}), ...options.headers}});
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    if(response.status === 401 && !path.startsWith('/auth/login')) {token=null;currentUser=null;sessionStorage.removeItem('centinel-token');updateSession();}
    throw new Error(Array.isArray(data.detail) ? data.detail.map(x => x.msg).join('; ') : data.detail || 'No fue posible conectar. Inténtalo de nuevo.');
  }
  return data;
}
function updateSession(){ $('#session-status').textContent=currentUser ? `${currentUser.full_name || currentUser.username} · ${translatedValue(currentUser.role)}` : 'Sesión de invitado';$('#session-button').textContent=currentUser ? '↪' : '↗';$('#session-button').setAttribute('aria-label',currentUser?'Cerrar sesión':'Iniciar sesión');}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500);}
function heading(title, description, action=''){return `<div class="page-heading"><div><span class="eyebrow">TU CENTRO DE SEGURIDAD</span><h1>${title}</h1><p class="sub">${description}</p></div>${action || `<span class="date">${new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(new Date())}</span>`}</div>`;}
function empty(title,detail,action=''){return `<div class="empty"><strong>${title}</strong>${detail}${action}</div>`;}
function signInPanel(){return `<section class="panel">${empty('Tu espacio está listo','Inicia sesión para ver las métricas en vivo y administrar tus espacios conectados.','<br><button class="button primary" data-action="login">Iniciar sesión ↗</button>')}</section>`;}
function stats(summary,cameras){return `<div class="stats">${[['Cámaras registradas',cameras?.length,'Dispositivos configurados','▣'],['Personas autorizadas',summary?.authorized_people,'Perfiles biométricos activos','♧'],['Intentos de acceso',summary?.access_attempts_24h,'En las últimas 24 horas','⇥'],['Alertas abiertas',summary?.unresolved_alerts,'Pendientes de revisión','◇']].map(([label,value,note,icon])=>`<article class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><div class="stat-value">${value ?? '—'}</div><span class="stat-note">${note}</span></article>`).join('')}</div>`;}
function modules(){return `<div class="section-head"><h2>Un poco de control. Mucha tranquilidad.</h2><span>Tu espacio, conectado</span></div><div class="modules">${[['cameras','▣','Vigila todos tus espacios','Consulta tus cámaras y configura la detección de cada ubicación.','Administrar cámaras'],['permissions','◇','El acceso correcto para cada persona','Administra el acceso biométrico y decide quién puede entrar a cada zona.','Administrar permisos'],['users','♧','Las personas son el centro de la seguridad','Consulta tu equipo, configura cuentas y administra los roles del sistema.','Administrar usuarios']].map(([page,icon,title,description,link])=>`<a class="module" href="#${page}"><span class="module-icon">${icon}</span><h3>${title}</h3><p>${description}</p><span class="module-link">${link}<span>↗</span></span></a>`).join('')}</div>`;}
function stopBrowserStream(){
 if(!browserStream)return;
 browserStream.getVideoTracks().forEach(track=>track.onended=null);
 browserStream.getTracks().forEach(track=>track.stop());browserStream=null;
}
function clearPreview(){browserRequest++;stopBrowserStream();if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null;}}
function clearCameraFeeds(){
 cameraFeeds.forEach(feed=>{feed.stopped=true;feed.controller?.abort();if(feed.analysisTimer)clearTimeout(feed.analysisTimer);});cameraFeeds.clear();
 cameraRecordings.forEach(recording=>{if(recording.recorder?.state!=='inactive')recording.recorder.stop();if(recording.url)URL.revokeObjectURL(recording.url);recording.stream?.getTracks().forEach(track=>track.stop());});cameraRecordings.clear();
}
function clearEnrollmentPhotos(){enrollmentPhotos.forEach(photo=>URL.revokeObjectURL(photo.url));enrollmentPhotos=[];}
async function render(){
 clearPreview();clearCameraFeeds();if($('#modal').open)$('#modal').close();
 const version=++generation;const page=titles[location.hash.slice(1)] ? location.hash.slice(1) : 'home';
 $('#breadcrumb').textContent=titles[page];document.title=`${titles[page]} · Visor`;
 document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const main=$('#main');main.innerHTML='<div class="loading">Cargando tu espacio…</div>';
 try{
 let content='';
 if(page==='home'||page==='dashboard'){
   const [summary,cameras]=token?await Promise.all([api('/dashboard/summary'),api('/cameras')]):[null,null];
   content=heading(page==='home'?'Todo a la vista. Todo bajo control.':'Una visión más clara de tu seguridad.',page==='home'?'Te damos la bienvenida a Visor, una forma más simple de administrar el acceso a tus espacios.':'Métricas de acceso en vivo de las últimas 24 horas.');
   if(page==='home')content+=`<section class="hero"><div><span class="eyebrow">ESPACIOS CONECTADOS. DECISIONES SEGURAS.</span><h2>La seguridad comienza con<br>una visión completa.</h2><p>Reúne tus cámaras, personas y permisos de acceso en un espacio simple.</p><a class="button" href="#dashboard">Abrir panel <span>↗</span></a></div><div class="radar" aria-hidden="true"><div class="shield">✓</div></div></section>`;
   content+=stats(summary,cameras);
   if(page==='home')content+=modules();
   if(page==='dashboard'&&summary){const total=summary.access_attempts_24h;content+=`<section class="panel"><div class="panel-head"><h2>Accesos de un vistazo</h2><span class="badge">Últimas 24 horas</span></div><div class="meter-row">${[['Permitidos',summary.granted_24h],['Denegados',summary.denied_24h]].map(([label,value])=>{let percent=total?Math.round(value/total*100):0;return `<div class="meter"><div class="meter-circle" style="--value:${percent}"><span>${total?percent+'%':'—'}</span></div><h2>${label}</h2><p>${value} de ${total} intentos</p></div>`;}).join('')}<div class="meter"><div class="meter-circle"><span>${summary.unresolved_alerts}</span></div><h2>Alertas abiertas</h2><p>Eventos de seguridad sin resolver</p></div></div></section>`;}
   if(!token)content+=signInPanel();
   else if(admin()){const logs=await api('/logs/access?limit=6');content+=`<section class="panel"><div class="panel-head"><h2>Actividad reciente</h2><span class="badge neutral">Últimos eventos de acceso</span></div>${logs.length?table(['Hora','Cámara / zona','Resultado'],logs.map(row=>`<tr><td>${escapeHTML(new Date(row.timestamp+'Z').toLocaleString('es-CL'))}</td><td>${escapeHTML(row.camera_id)}<small>${escapeHTML(row.zone)}</small></td><td><span class="badge ${row.access_granted?'':'warning'}">${row.access_granted?'Permitido':'Denegado'}</span></td></tr>`)):empty('Todo tranquilo','La actividad de acceso aparecerá aquí cuando lleguen eventos de reconocimiento.')}</section>`;}
 } else if(!token){content=heading(titles[page],'Tu centro de seguridad, todo en un solo lugar.')+signInPanel();}
 else if(['users','biometrics','permissions','settings'].includes(page)&&!admin()){content=heading(titles[page],'Administración del sistema')+`<section class="panel">${empty('Se requiere acceso de administrador','Tu cuenta puede ver el panel y las cámaras. Comunícate con el administrador para cambiar la configuración.')}</section>`;}
 else if(page==='cameras'){
   const rows=await api('/cameras');content=heading('Todas las cámaras. Una sola vista.','Administra los dispositivos que vigilan tus espacios.',admin()?'<div class="toolbar"><button class="button" data-action="discover">⌕ Buscar dispositivos</button><button class="button primary" data-action="new-camera">＋ Agregar cámara</button></div>':'');
   content+='<div class="toolbar"><button class="button" data-action="browser-camera">Usar la cámara de este dispositivo</button></div>';
   content+='<div class="notice">Busca cámaras conectadas al servidor o a su red local. La prueba captura una imagen cuando la solicitas; no graba ni supervisa video de forma continua.</div>';
   content+='<div class="toolbar"><input class="search" type="search" placeholder="Buscar cámaras o zonas…" aria-label="Buscar cámaras" id="search"></div>';
   content+=rows.length?`<div class="camera-grid">${rows.map(c=>`<article class="panel camera-card" data-camera-card="${c.id}" data-search="${escapeHTML(c.name+' '+c.zone)}"><div class="camera-preview live-preview"><canvas class="camera-feed" data-feed="${c.id}" aria-label="Vista en vivo de ${escapeHTML(c.name)}"></canvas><span class="feed-placeholder">▣<br>${c.enabled?'Conectando…':'Cámara desactivada'}</span><span class="fullscreen-hint">Presiona Esc para salir</span></div><p class="feed-status" data-feed-status="${c.id}">${c.enabled?'Esperando la primera imagen…':''}</p><h3>${escapeHTML(c.name)}</h3><p class="sub">${escapeHTML(c.zone)} · detección de ${escapeHTML(translatedValue(c.detection))}</p><span class="badge ${c.enabled?'warning':'neutral'}">${c.enabled?'Activada':'Desactivada'}</span><button class="button fullscreen-button" data-fullscreen-camera="${c.id}" ${c.enabled?'':'disabled'}>⛶ Ver en pantalla completa</button>${admin()?`<div class="record-controls"><button class="button primary" data-record="${c.id}" ${c.enabled?'':'disabled'}>● Grabar</button><button class="button" data-pause-recording="${c.id}" disabled>Pausar</button><button class="button" data-stop-recording="${c.id}" disabled>Detener</button></div><div class="recording-result" data-recording-result="${c.id}"></div><button class="button biometric-button" data-enroll-camera="${c.id}" ${c.enabled?'':'disabled'}>◎ Agregar datos biométricos</button><button class="button" data-camera="${c.id}">Configurar cámara ↗</button><button class="button" data-preview="${c.id}" ${c.enabled?'':'disabled'}>Probar captura</button>`:''}</article>`).join('')}</div>`:`<section class="panel">${empty('Realiza tu primera conexión','Agrega una cámara para organizar tus dispositivos y sus ajustes de detección.')}</section>`;
   window.cameraRows=rows;
 }else if(page==='biometrics'){
   content=heading('Agregar datos biométricos','Registra a una persona para que el servicio de reconocimiento pueda identificarla.');
   content+='<div class="notice">El registro biométrico requiere el consentimiento explícito de la persona. Las fotos se procesan para crear una plantilla facial cifrada y no se almacenan.</div>';
   content+=`<section class="panel enrollment-panel"><form id="enrollment-form"><div class="form-grid">${field('employee_id','Identificador de la persona','','text','maxlength="50" placeholder="EMP-001"')}${field('full_name','Nombre completo','','text','maxlength="255"')}${field('department','Departamento','','text','maxlength="100" placeholder="Opcional"')}${field('authorized_zones','Zonas autorizadas','','text','maxlength="500" placeholder="Entrada, Oficina (vacío permite todas)"')}</div><label for="field-images">Fotos del rostro</label><input id="field-images" name="images" type="file" accept="image/jpeg,image/png" multiple required><p class="sub">Selecciona entre 3 y 5 fotos claras de la misma persona: de frente, ligeramente hacia la izquierda y hacia la derecha. Cada imagen debe contener un solo rostro y pesar como máximo 8 MB.</p>${check('consent_given','La persona dio su consentimiento explícito para procesar y almacenar su plantilla biométrica cifrada',false)}<p id="enrollment-error" class="error" role="alert"></p><p id="enrollment-success" class="success" role="status"></p><button class="button primary" type="submit" id="enroll-button">Guardar perfil biométrico</button></form></section>`;
 }else if(page==='users'){
   const rows=await api('/users');window.userRows=rows;content=heading('Tu equipo, conectado.','Administra las cuentas y los roles de tu equipo de seguridad.','<button class="button primary" data-action="new-user">＋ Agregar usuario</button>')+'<input class="search" id="search" type="search" placeholder="Buscar personas…" aria-label="Buscar usuarios">';
   content+=`<section class="panel">${table(['Integrante','Usuario','Rol','Estado',''],rows.map(u=>`<tr data-search="${escapeHTML(u.full_name+' '+u.email+' '+u.username)}"><td>${escapeHTML(u.full_name)}<small>${escapeHTML(u.email)}</small></td><td>${escapeHTML(u.username)}</td><td>${escapeHTML(translatedValue(u.role))}</td><td><span class="badge ${u.is_active?'':'neutral'}">${u.is_active?'Activo':'Inactivo'}</span></td><td><button class="button" data-user="${u.id}" aria-label="Configurar a ${escapeHTML(u.full_name)}">Configurar ↗</button></td></tr>`))}</section>`;
 }else if(page==='permissions'){
   const rows=await api('/permissions');window.personRows=rows;content=heading('Acceso con criterio.','Define los permisos por zona para los perfiles biométricos registrados.');content+='<div class="notice">Los roles del sistema se administran en Usuarios. Los perfiles biométricos se registran con consentimiento explícito.</div>';
   content+=`<section class="panel">${rows.length?table(['Persona','Zonas autorizadas','Acceso',''],rows.map(p=>`<tr><td>${escapeHTML(p.full_name)}<small>${escapeHTML(p.employee_id)} · ${escapeHTML(p.department)}</small></td><td>${escapeHTML(p.authorized_zones||'Todas las zonas')}</td><td><span class="badge ${p.is_active?'':'neutral'}">${p.is_active?'Activado':'Desactivado'}</span></td><td><button class="button" data-person="${p.id}">Editar permisos ↗</button></td></tr>`)):empty('Aún no hay perfiles registrados','Registra a una persona con su consentimiento para administrar el acceso a las zonas.','<br><a class="button" href="#biometrics">Agregar datos biométricos ↗</a>')}</section>`;
 }else{content=heading('Haz tuyo este espacio.','Configura dispositivos, cuentas y accesos desde un solo lugar.')+modules()+`<section class="panel"><h2>Conexiones de dispositivos</h2><p class="sub">Busca dispositivos de captura USB locales, cámaras ONVIF en la red del servidor o dispositivos Bluetooth conectados. Un dispositivo Bluetooth necesita un controlador de video compatible o una transmisión Wi-Fi.</p><button class="button primary" data-action="discover">Buscar dispositivos</button><a class="button" href="#cameras">Configurar cámaras ↗</a></section><section class="panel"><h2>Configuración de la cuenta</h2><p class="sub">Sesión iniciada como ${escapeHTML(currentUser.email)}. Actualiza nombres, correos, roles y el estado de las cuentas desde Usuarios.</p><a class="button" href="#users">Configurar usuarios ↗</a></section>`;}
 if(version===generation){main.innerHTML=content;if(page==='cameras')startCameraFeeds(window.cameraRows.filter(camera=>camera.enabled));if(page==='biometrics'&&admin())setupEnrollmentForm();}
 }catch(error){if(version===generation)main.innerHTML=heading(titles[page],'Espacio de trabajo')+`<section class="panel">${empty('No pudimos cargar esta página',escapeHTML(error.message),'<br><button class="button" data-action="retry">Intentar de nuevo</button>')}</section>`;}
}
function startCameraFeeds(cameras){cameras.forEach(camera=>{const feed={stopped:false,controller:new AbortController(),zone:camera.zone,detections:null,lastJpeg:null,analyzing:false,analysisTimer:null,analyze:admin()};cameraFeeds.set(camera.id,feed);streamCameraFeed(camera.id);});}
function drawFaceBoxes(canvas,detections){const context=canvas.getContext('2d'),scaleX=canvas.width/(detections.width||canvas.width),scaleY=canvas.height/(detections.height||canvas.height);context.font='600 16px system-ui';context.lineWidth=Math.max(3,canvas.width/320);detections.faces.forEach(face=>{const color=face.status==='allowed'?'#20d46b':'#ef4444',x=face.box.left*scaleX,y=face.box.top*scaleY,width=(face.box.right-face.box.left)*scaleX,height=(face.box.bottom-face.box.top)*scaleY,label=face.status==='allowed'?`✓ ${face.label}`:face.status==='denied'?`✕ ${face.label} · Sin acceso`:'✕ Sin registrar';context.strokeStyle=color;context.strokeRect(x,y,width,height);const textWidth=context.measureText(label).width+14,textY=Math.max(22,y);context.fillStyle=color;context.fillRect(x,textY-22,textWidth,22);context.fillStyle='#fff';context.fillText(label,x+7,textY-6);});}
async function streamCameraFeed(id){
 const feed=cameraFeeds.get(id),canvas=document.querySelector(`[data-feed="${id}"]`),status=document.querySelector(`[data-feed-status="${id}"]`);if(!feed||feed.stopped||!canvas)return;
 try{const response=await fetch('/api/cameras/'+id+'/stream',{headers:{Authorization:'Bearer '+token},signal:feed.controller.signal});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.detail||'Transmisión de la cámara no disponible');}const reader=response.body.getReader();let buffer=new Uint8Array(0);
 while(!feed.stopped){const {done,value}=await reader.read();if(done)break;const merged=new Uint8Array(buffer.length+value.length);merged.set(buffer);merged.set(value,buffer.length);buffer=merged;while(buffer.length>=4){const size=new DataView(buffer.buffer,buffer.byteOffset,4).getUint32(0);if(size<2||size>4*1024*1024)throw new Error('Imagen de cámara no válida');if(buffer.length<4+size)break;const jpeg=buffer.slice(4,4+size);buffer=buffer.slice(4+size);feed.lastJpeg=new Blob([jpeg],{type:'image/jpeg'});const bitmap=await createImageBitmap(feed.lastJpeg);if(feed.stopped||!canvas.isConnected){bitmap.close();return;}canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();if(feed.detections?.faces?.length)drawFaceBoxes(canvas,feed.detections);canvas.parentElement.classList.add('has-frame');if(feed.analyze&&!feed.analysisTimer)feed.analysisTimer=setTimeout(()=>analyzeCameraFeed(id),500);const recorder=cameraRecordings.get(id)?.recorder;status.textContent=recorder?.state==='recording'?'Grabando…':recorder?.state==='paused'?'Grabación pausada':'En vivo · '+new Date().toLocaleTimeString('es-CL');}}
 if(!feed.stopped)throw new Error('Cámara desconectada');
 }catch(error){if(error.name!=='AbortError'&&status?.isConnected)status.textContent=error.message;}
}
async function analyzeCameraFeed(id){const feed=cameraFeeds.get(id);if(!feed||feed.stopped)return;feed.analysisTimer=null;if(feed.analyzing||!feed.lastJpeg){feed.analysisTimer=setTimeout(()=>analyzeCameraFeed(id),1000);return;}feed.analyzing=true;try{const form=new FormData();form.append('image',feed.lastJpeg,`camera-${id}.jpg`);form.append('zone',feed.zone);const result=await api('/access/analyze',{method:'POST',body:form});if(!feed.stopped)feed.detections=result;}catch(error){if(error.name!=='AbortError'){const status=document.querySelector(`[data-feed-status="${id}"]`);if(status?.isConnected)status.textContent='Reconocimiento: '+error.message;}}finally{feed.analyzing=false;if(!feed.stopped)feed.analysisTimer=setTimeout(()=>analyzeCameraFeed(id),1200);}}
function recordingButtons(id,isRecording,isPaused=false){const start=document.querySelector(`[data-record="${id}"]`),pause=document.querySelector(`[data-pause-recording="${id}"]`),stop=document.querySelector(`[data-stop-recording="${id}"]`);if(!start)return;start.disabled=isRecording;pause.disabled=!isRecording;pause.textContent=isPaused?'Reanudar':'Pausar';stop.disabled=!isRecording;}
function startCameraRecording(id){
 const canvas=document.querySelector(`[data-feed="${id}"]`),status=document.querySelector(`[data-feed-status="${id}"]`);if(!canvas?.width){toast('Espera a que la cámara muestre la primera imagen');return;}if(!window.MediaRecorder||!canvas.captureStream){toast('Este navegador no permite grabar la cámara');return;}
 const stream=canvas.captureStream(10),mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(type=>MediaRecorder.isTypeSupported(type))||'',chunks=[],recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined),recording={recorder,stream,chunks,url:null};cameraRecordings.set(id,recording);
 recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=()=>finishCameraRecording(id);recorder.start(1000);recordingButtons(id,true);status.textContent='Grabando…';
}
function pauseCameraRecording(id){const recording=cameraRecordings.get(id);if(!recording||recording.recorder.state==='inactive')return;const pause=recording.recorder.state==='recording';pause?recording.recorder.pause():recording.recorder.resume();recordingButtons(id,true,pause);const status=document.querySelector(`[data-feed-status="${id}"]`);if(status)status.textContent=pause?'Grabación pausada':'Grabando…';}
function stopCameraRecording(id){const recording=cameraRecordings.get(id);if(recording?.recorder.state!=='inactive')recording.recorder.stop();}
function finishCameraRecording(id){const recording=cameraRecordings.get(id),result=document.querySelector(`[data-recording-result="${id}"]`);if(!recording)return;recording.stream.getTracks().forEach(track=>track.stop());recording.url=URL.createObjectURL(new Blob(recording.chunks,{type:recording.recorder.mimeType||'video/webm'}));recordingButtons(id,false);if(result)result.innerHTML=`<video controls src="${recording.url}" class="recorded-video"></video><div class="record-actions"><a class="button" href="${recording.url}" download="camera-${id}-${Date.now()}.webm">Descargar video</a><button class="button danger" data-delete-recording="${id}">Eliminar video</button></div>`;}
function deleteCameraRecording(id){const recording=cameraRecordings.get(id);if(!recording)return;if(recording.recorder.state!=='inactive')recording.recorder.stop();if(recording.url)URL.revokeObjectURL(recording.url);recording.stream?.getTracks().forEach(track=>track.stop());cameraRecordings.delete(id);const result=document.querySelector(`[data-recording-result="${id}"]`);if(result)result.innerHTML='';recordingButtons(id,false);toast('Video eliminado');}
let expandedPreview=null;
async function openCameraFullscreen(id){
 const canvas=document.querySelector(`[data-feed="${id}"]`),preview=canvas?.parentElement;if(!preview)return;
 expandedPreview=preview;
 if(preview.requestFullscreen){try{await preview.requestFullscreen();return;}catch(error){/* Usa la vista ampliada si el navegador rechaza Fullscreen API. */}}
 preview.classList.add('expanded-preview');document.body.classList.add('camera-expanded');
}
function closeCameraFullscreen(){
 if(document.fullscreenElement&&document.exitFullscreen){document.exitFullscreen();return;}
 expandedPreview?.classList.remove('expanded-preview');document.body.classList.remove('camera-expanded');expandedPreview=null;
}
function table(headings,rows){return `<div class="table-wrap"><table><thead><tr>${headings.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function setupEnrollmentForm(){
 const form=$('#enrollment-form');if(!form)return;form.onsubmit=async event=>{event.preventDefault();const error=$('#enrollment-error'),success=$('#enrollment-success'),button=$('#enroll-button'),files=form.elements.images.files;error.textContent='';success.textContent='';
 if(files.length<3||files.length>5){error.textContent='Selecciona entre 3 y 5 fotos del rostro.';return;}if([...files].some(file=>!['image/jpeg','image/png'].includes(file.type)||file.size>8*1024*1024)){error.textContent='Cada foto debe ser JPEG o PNG y pesar como máximo 8 MB.';return;}if(!form.elements.consent_given.checked){error.textContent='Se requiere el consentimiento biométrico explícito.';return;}
 button.disabled=true;button.textContent='Creando plantilla cifrada…';try{const person=await api('/access/enroll',{method:'POST',body:new FormData(form)});form.reset();success.textContent=`${person.full_name} se registró correctamente. El reconocimiento ya está habilitado para este perfil.`;toast('Perfil biométrico guardado');}catch(reason){error.textContent=reason.message;}finally{button.disabled=false;button.textContent='Guardar perfil biométrico';}};
}
function cameraEnrollment(id){
 clearEnrollmentPhotos();enrollmentCameraId=id;
 $('#dialog-title').textContent='Agregar datos biométricos';$('#form-error').textContent='';$('#save-button').hidden=false;$('#save-button').textContent='Guardar perfil biométrico';
 $('#fields').innerHTML='<p class="sub">Captura entre 3 y 5 fotos con esta cámara. Pide a la persona que mire al frente, ligeramente a la izquierda y a la derecha.</p>'+field('employee_id','Identificador de la persona','','text','maxlength="50" placeholder="EMP-001"')+field('full_name','Nombre completo','','text','maxlength="255"')+field('department','Departamento','','text','maxlength="100" placeholder="Opcional"')+field('authorized_zones','Zonas autorizadas','','text','maxlength="500" placeholder="Entrada, Oficina (vacío permite todas)"')+check('consent_given','La persona dio su consentimiento explícito para el procesamiento biométrico',false)+'<button type="button" class="button capture-biometric" data-capture-biometric="'+id+'">Capturar foto</button><p id="capture-status" class="sub" role="status">0 de un mínimo de 3 fotos capturadas.</p><div id="biometric-thumbnails" class="biometric-thumbnails"></div>';
 $('#editor').onsubmit=async event=>{event.preventDefault();const button=$('#save-button');$('#form-error').textContent='';if(enrollmentPhotos.length<3){$('#form-error').textContent='Captura al menos 3 fotos.';return;}const form=new FormData(event.target);enrollmentPhotos.forEach((photo,index)=>form.append('images',photo.blob,`camera-${id}-${index+1}.jpg`));button.disabled=true;button.textContent='Creando plantilla cifrada…';try{const person=await api('/access/enroll',{method:'POST',body:form});$('#modal').close();toast(`${person.full_name} se registró correctamente`);await render();}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;button.textContent='Guardar perfil biométrico';}};$('#modal').showModal();
}
async function captureBiometricPhoto(id){
 const status=$('#capture-status'),button=document.querySelector('[data-capture-biometric]');if(enrollmentPhotos.length>=5){status.textContent='Se alcanzó el máximo de 5 fotos.';return;}button.disabled=true;status.textContent='Capturando foto…';
 try{const response=await fetch('/api/cameras/'+id+'/snapshot',{method:'POST',headers:{Authorization:'Bearer '+token}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.detail||'No se pudo capturar una imagen');}const blob=await response.blob(),url=URL.createObjectURL(blob);enrollmentPhotos.push({blob,url});$('#biometric-thumbnails').innerHTML=enrollmentPhotos.map((photo,index)=>`<figure><img src="${photo.url}" alt="Captura biométrica ${index+1}"><button type="button" class="icon-button" data-remove-biometric="${index}" aria-label="Eliminar foto ${index+1}">×</button></figure>`).join('');status.textContent=`${enrollmentPhotos.length} de un mínimo de 3 fotos capturadas.${enrollmentPhotos.length>=3?' Listo para guardar.':''}`;
 }catch(error){status.textContent=error.message;}finally{button.disabled=enrollmentPhotos.length>=5;}
}
function removeBiometricPhoto(index){const photo=enrollmentPhotos.splice(index,1)[0];if(photo)URL.revokeObjectURL(photo.url);const container=$('#biometric-thumbnails');if(container)container.innerHTML=enrollmentPhotos.map((item,position)=>`<figure><img src="${item.url}" alt="Captura biométrica ${position+1}"><button type="button" class="icon-button" data-remove-biometric="${position}" aria-label="Eliminar foto ${position+1}">×</button></figure>`).join('');const status=$('#capture-status');if(status)status.textContent=`${enrollmentPhotos.length} de un mínimo de 3 fotos capturadas.`;const button=document.querySelector('[data-capture-biometric]');if(button)button.disabled=false;}
function field(name,label,value='',type='text',extra=''){return `<label for="field-${name}">${label}</label><input id="field-${name}" name="${name}" type="${type}" value="${escapeHTML(value)}" required ${extra}>`;}
function select(name,label,values,value){return `<label for="field-${name}">${label}</label><select id="field-${name}" name="${name}">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${translatedValue(v)}</option>`).join('')}</select>`;}
function check(name,label,value){return `<label class="check"><input name="${name}" type="checkbox" ${value?'checked':''}>${label}</label>`;}
function dialog(title,fields,save,label='Guardar cambios'){
 clearPreview();$('#save-button').hidden=false;$('#dialog-title').textContent=title;$('#fields').innerHTML=fields;$('#form-error').textContent='';$('#save-button').textContent=label;$('#modal').showModal();
 $('#editor').onsubmit=async event=>{event.preventDefault();const button=$('#save-button');button.disabled=true;$('#form-error').textContent='';try{await save(new FormData(event.target));$('#modal').close();toast(title==='Iniciar sesión'?'Te damos la bienvenida':'Cambios guardados');await render();}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;}};
}
function login(){dialog('Iniciar sesión','<p class="sub">Te damos la bienvenida. Usa tu cuenta del sistema.</p>'+field('username','Correo electrónico','','email','autocomplete="username"')+field('password','Contraseña','','password','autocomplete="current-password"'),async form=>{const result=await api('/auth/login',{method:'POST',body:new URLSearchParams(form)});token=result.access_token;sessionStorage.setItem('centinel-token',token);currentUser=await api('/auth/me');updateSession();},'Iniciar sesión →');}
function cameraEditor(c){dialog(c?.id?'Configurar cámara':'Agregar cámara',field('name','Nombre de la cámara',c?.name,'text','maxlength="100"')+field('zone','Zona',c?.zone,'text','maxlength="100"')+field('source','Fuente de video',c?.source,'text','placeholder="/dev/video0 o rtsp://192.168.1.10/stream" maxlength="500"')+'<p class="sub">Local: /dev/videoN. Red: transmisión RTSP o URL de captura JPEG por HTTP, con una IP privada y sin credenciales incrustadas. La captura de red requiere incluir esa IP en CAMERA_ALLOWED_HOSTS del servidor. Una URL de servicio ONVIF no es una URL de video.</p>'+select('detection','Modo de detección',['both','face','animal'],c?.detection||'both')+'<p class="sub">El modo se guarda para la integración de reconocimiento; la vista previa solo comprueba la captura de video.</p>'+check('enabled','Activar cámara',c?.enabled??true)+(c?.id?'<button type="button" class="button danger" data-remove="'+c.id+'">Eliminar cámara</button>':''),form=>api('/cameras'+(c?.id?'/'+c.id:''),{method:c?.id?'PUT':'POST',body:JSON.stringify({...Object.fromEntries(form),enabled:form.has('enabled')})}));}
function discoveryPanel(){
 discoveryRows=[];$('#dialog-title').textContent='Buscar dispositivos de cámara';$('#form-error').textContent='';$('#save-button').hidden=true;
 $('#fields').innerHTML='<p class="sub">La búsqueda se ejecuta en el servidor Python, no en el equipo que muestra esta página.</p><div class="discovery-tabs"><button type="button" class="button" data-discover="usb">USB / local</button><button type="button" class="button" data-discover="network">Wi-Fi / red</button><button type="button" class="button" data-discover="bluetooth">Bluetooth</button></div><div id="discovery-results" role="status" aria-live="polite">Elige un tipo de conexión para buscar.</div>';
 $('#editor').onsubmit=event=>event.preventDefault();$('#modal').showModal();
}
async function discoverDevices(transport){
 const results=$('#discovery-results');if(!results)return;
 document.querySelectorAll('[data-discover]').forEach(button=>button.disabled=true);
 results.textContent='Buscando dispositivos…';
 try{const data=await api('/cameras/discovery/'+transport,{method:'POST'});if(!results.isConnected)return;
 discoveryRows=data.devices;results.innerHTML='<p class="sub">'+escapeHTML(data.message)+'</p>'+data.devices.map((device,index)=>'<article class="discovered-device"><strong>'+escapeHTML(device.name)+'</strong><p class="sub">'+escapeHTML(device.source||device.address)+' · '+escapeHTML(device.status.replaceAll('_',' '))+'</p>'+(device.can_register?'<button type="button" class="button" data-register="'+index+'">'+(device.transport==='network'?'Definir URL de transmisión':'Agregar cámara')+'</button>':'<span class="badge warning">Se requiere un controlador de video</span>')+'</article>').join('')+(!data.devices.length?'<p class="sub">No se encontraron dispositivos. Revisa la conexión y los permisos del servidor e inténtalo de nuevo.</p>':'');
 }catch(error){if(results.isConnected)results.textContent=error.message;}
 finally{document.querySelectorAll('[data-discover]').forEach(button=>button.disabled=false);}
}
async function previewCamera(id){
 clearPreview();$('#dialog-title').textContent='Prueba de conexión de la cámara';$('#form-error').textContent='';$('#save-button').hidden=true;$('#fields').innerHTML='<p id="preview-status" class="sub" role="status">Abriendo cámara… (hasta 8 segundos)</p><div id="preview-image"></div>';$('#editor').onsubmit=event=>event.preventDefault();$('#modal').showModal();
 const status=$('#preview-status');const authToken=token;
 try{const response=await fetch('/api/cameras/'+id+'/snapshot',{method:'POST',headers:{Authorization:'Bearer '+authToken}});
 if(!response.ok){const error=await response.json();throw new Error(error.detail||'Falló la prueba de la cámara');}
 const blob=await response.blob();if(!status.isConnected||!$('#modal').open||token!==authToken)return;
 previewURL=URL.createObjectURL(blob);const img=document.createElement('img');img.src=previewURL;img.alt='Captura de prueba de la cámara';img.className='snapshot';$('#preview-image').append(img);status.textContent='Imagen recibida a las '+new Date().toLocaleTimeString('es-CL')+'. Esta es una captura, no una transmisión en vivo.';
 }catch(error){if(status.isConnected)status.textContent=error.message;}
}
function browserCamera(){
 clearPreview();$('#dialog-title').textContent='Cámara de este dispositivo';$('#form-error').textContent='';$('#save-button').hidden=true;
 $('#fields').innerHTML='<p class="sub">Previsualiza la cámara del computador o teléfono que usa este navegador. El video permanece en el navegador: no se graba ni se envía al servidor. Para ver la cámara de un teléfono a distancia, configura su transmisión Wi-Fi en Cámaras.</p><p id="browser-status" class="sub" role="status"></p><label for="browser-device">Cámara</label><select id="browser-device" aria-label="Seleccionar cámara" disabled><option>Detectando cámaras…</option></select><video id="browser-video" class="snapshot" autoplay muted playsinline></video>';
 $('#editor').onsubmit=event=>event.preventDefault();$('#modal').showModal();
 $('#browser-device').onchange=event=>startBrowserCamera(event.target.value);startBrowserCamera();
}
async function startBrowserCamera(deviceId){
 const request=++browserRequest;stopBrowserStream();const status=$('#browser-status'),selector=$('#browser-device');
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){status.textContent='El acceso a la cámara requiere HTTPS o localhost en este dispositivo. Usa una dirección HTTPS de confianza al abrir el sistema desde un teléfono.';return;}
 selector.disabled=true;status.textContent=deviceId?'Cambiando de cámara…':'Esperando permiso para usar la cámara…';
 try{
 const stream=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'}},audio:false});
 if(request!==browserRequest||!status.isConnected||!$('#modal').open){stream.getTracks().forEach(track=>track.stop());return;}
 browserStream=stream;const video=$('#browser-video');video.srcObject=stream;await video.play();
 const devices=await navigator.mediaDevices.enumerateDevices();if(request!==browserRequest||!status.isConnected)return;
 const selected=stream.getVideoTracks()[0].getSettings().deviceId,videoInputs=devices.filter(device=>device.kind==='videoinput');
 selector.innerHTML=videoInputs.map((device,index)=>'<option value="'+escapeHTML(device.deviceId)+'" '+(device.deviceId===selected?'selected':'')+'>'+escapeHTML(device.label||'Cámara '+(index+1))+'</option>').join('');selector.disabled=videoInputs.length<2;
 status.textContent='Cámara conectada. Cierra esta ventana para detenerla.';
 stream.getVideoTracks()[0].onended=()=>{if(request===browserRequest&&status.isConnected)status.textContent='La cámara se desconectó o se revocó el permiso. Cierra y vuelve a abrir para reconectarla.';};
 }catch(error){if(request===browserRequest&&status.isConnected){stopBrowserStream();selector.disabled=false;status.textContent=error.name==='NotAllowedError'?'Permiso de cámara denegado. Permite el acceso en la configuración del navegador e inténtalo de nuevo.':error.name==='NotFoundError'||error.name==='OverconstrainedError'?'La cámara seleccionada ya no está disponible. Elige otra o vuelve a conectarla.':'No se pudo abrir la cámara. Cierra otras aplicaciones que la estén usando e inténtalo de nuevo.';}}
}
function removeCamera(id){dialog('Eliminar cámara','<p class="sub">¿Quieres eliminar la configuración de esta cámara? Los registros de acceso existentes se conservarán.</p>',()=>api('/cameras/'+id,{method:'DELETE'}),'Eliminar cámara');}

function userEditor(u){dialog(u?'Configurar usuario':'Agregar usuario',field('full_name','Nombre completo',u?.full_name,'text','maxlength="255"')+field('email','Correo electrónico',u?.email,'email')+(!u?field('username','Nombre de usuario','','text','minlength="3" maxlength="100"')+field('password','Contraseña','','password','minlength="12" maxlength="128" autocomplete="new-password"'):'')+select('role','Rol del sistema',['security','user','admin'],u?.role||'security')+(u?check('is_active','Cuenta activa',u.is_active):''),form=>api('/users'+(u?'/'+u.id:''),{method:u?'PUT':'POST',body:JSON.stringify({...Object.fromEntries(form),...(u?{is_active:form.has('is_active')}:{})})}));}
function permissionEditor(p){dialog('Editar permisos',`<p class="sub">${escapeHTML(p.full_name)} · ${escapeHTML(p.employee_id)}</p><label for="zones">Zonas autorizadas</label><input id="zones" name="authorized_zones" maxlength="500" value="${escapeHTML(p.authorized_zones)}" placeholder="Recepción, Oficina"><p class="sub">Separa los nombres exactos de las zonas con comas. Si lo dejas vacío, se permitirá el acceso a todas las zonas.</p>`+check('is_active','Permitir acceso biométrico',p.is_active),form=>api('/permissions/'+p.id,{method:'PUT',body:JSON.stringify({authorized_zones:form.get('authorized_zones'),is_active:form.has('is_active')})}));}
$('#close-modal').onclick=()=>$('#modal').close();
$('#modal').addEventListener('close',()=>{clearPreview();clearEnrollmentPhotos();enrollmentCameraId=null;$('#save-button').hidden=false;});
$('#session-button').onclick=()=>{if(!token)return login();token=null;currentUser=null;sessionStorage.removeItem('centinel-token');updateSession();render();};
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const action=button.dataset.action;if(action==='browser-camera')browserCamera();if(action==='discover')discoveryPanel();if(action==='login')login();if(action==='retry')render();if(action==='new-camera')cameraEditor();if(action==='new-user')userEditor();if(button.dataset.fullscreenCamera)openCameraFullscreen(Number(button.dataset.fullscreenCamera));if(button.dataset.discover)discoverDevices(button.dataset.discover);if(button.dataset.preview)previewCamera(Number(button.dataset.preview));if(button.dataset.record)startCameraRecording(Number(button.dataset.record));if(button.dataset.pauseRecording)pauseCameraRecording(Number(button.dataset.pauseRecording));if(button.dataset.stopRecording)stopCameraRecording(Number(button.dataset.stopRecording));if(button.dataset.deleteRecording)deleteCameraRecording(Number(button.dataset.deleteRecording));if(button.dataset.enrollCamera)cameraEnrollment(Number(button.dataset.enrollCamera));if(button.dataset.captureBiometric)captureBiometricPhoto(Number(button.dataset.captureBiometric));if(button.dataset.removeBiometric!==undefined)removeBiometricPhoto(Number(button.dataset.removeBiometric));if(button.dataset.remove)removeCamera(Number(button.dataset.remove));if(button.dataset.register!==undefined){const device=discoveryRows[Number(button.dataset.register)];cameraEditor({name:device.name,source:device.source,zone:''});}if(button.dataset.camera)cameraEditor(window.cameraRows.find(c=>c.id===Number(button.dataset.camera)));if(button.dataset.user)userEditor(window.userRows.find(u=>u.id===Number(button.dataset.user)));if(button.dataset.person)permissionEditor(window.personRows.find(p=>p.id===Number(button.dataset.person)));});
document.addEventListener('input',event=>{if(event.target.id==='search'){const query=event.target.value.toLowerCase();document.querySelectorAll('[data-search]').forEach(row=>row.hidden=!row.dataset.search.toLowerCase().includes(query));}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&expandedPreview)closeCameraFullscreen();});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement){expandedPreview?.classList.remove('expanded-preview');document.body.classList.remove('camera-expanded');expandedPreview=null;}});
window.addEventListener('hashchange',render);
window.addEventListener('pagehide',()=>{clearPreview();clearCameraFeeds();});
(async()=>{if(token){try{currentUser=await api('/auth/me');}catch{token=null;sessionStorage.removeItem('centinel-token');}}updateSession();render();})();
